In [1]:
import pandas as pd
from datetime import timedelta

In [2]:
hos = pd.read_csv("data/COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_State_Timeseries__RAW__20240228.csv")
hos.head()

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,previous_day_admission_pediatric_covid_confirmed_5_11,previous_day_admission_pediatric_covid_confirmed_5_11_coverage,previous_day_admission_pediatric_covid_confirmed_unknown,previous_day_admission_pediatric_covid_confirmed_unknown_coverage,staffed_icu_pediatric_patients_confirmed_covid,staffed_icu_pediatric_patients_confirmed_covid_coverage,staffed_pediatric_icu_bed_occupancy,staffed_pediatric_icu_bed_occupancy_coverage,total_staffed_pediatric_icu_beds,total_staffed_pediatric_icu_beds_coverage
0,NH,2021/05/23,3,26,1,5,24,1,0.0,30,...,NaN,0,NaN,0,NaN,0,27.0,16,39.0,16
1,KS,2021/05/21,11,135,4,13,133,4,0.0,147,...,NaN,0,NaN,0,NaN,0,77.0,147,274.0,147
2,MT,2021/05/19,5,61,1,5,61,1,3.0,66,...,NaN,0,NaN,0,NaN,0,7.0,15,18.0,15
3,MO,2021/05/18,22,82,19,26,78,19,4.0,119,...,NaN,0,NaN,0,NaN,0,582.0,119,850.0,119
4,NV,2021/05/18,0,1,59,0,1,59,21.0,58,...,NaN,0,NaN,0,NaN,0,0.0,1,0.0,1

In [3]:
# Columns to keep
cols = ['state', 
        'date',
        'previous_day_admission_adult_covid_confirmed_18-19',
        'previous_day_admission_adult_covid_confirmed_20-29',
        'previous_day_admission_adult_covid_confirmed_30-39',
        'previous_day_admission_adult_covid_confirmed_40-49',
        'previous_day_admission_adult_covid_confirmed_50-59',
        'previous_day_admission_adult_covid_confirmed_60-69',
        'previous_day_admission_adult_covid_confirmed_70-79',
        'previous_day_admission_adult_covid_confirmed_80+',
        'previous_day_admission_adult_covid_confirmed_unknown',
        'critical_staffing_shortage_today_yes'
        ]
hos = hos[cols]
hos.head()

,state,date,previous_day_admission_adult_covid_confirmed_18-19,previous_day_admission_adult_covid_confirmed_20-29,previous_day_admission_adult_covid_confirmed_30-39,previous_day_admission_adult_covid_confirmed_40-49,previous_day_admission_adult_covid_confirmed_50-59,previous_day_admission_adult_covid_confirmed_60-69,previous_day_admission_adult_covid_confirmed_70-79,previous_day_admission_adult_covid_confirmed_80+,previous_day_admission_adult_covid_confirmed_unknown,critical_staffing_shortage_today_yes
0,NH,2021/05/23,0.0,0.0,0.0,0.0,2.0,1.0,1.0,2.0,0.0,3
1,KS,2021/05/21,1.0,1.0,2.0,5.0,2.0,7.0,5.0,5.0,1.0,11
2,MT,2021/05/19,0.0,1.0,1.0,1.0,4.0,3.0,3.0,3.0,0.0,5
3,MO,2021/05/18,0.0,4.0,4.0,4.0,8.0,11.0,8.0,4.0,2.0,22
4,NV,2021/05/18,0.0,2.0,4.0,6.0,9.0,6.0,5.0,9.0,0.0,0

In [4]:
# Sort the hos by date and state
hos.sort_values(by=['date', 'state'], inplace=True)
hos.reset_index(drop=True, inplace=True)
hos.head()

,state,date,previous_day_admission_adult_covid_confirmed_18-19,previous_day_admission_adult_covid_confirmed_20-29,previous_day_admission_adult_covid_confirmed_30-39,previous_day_admission_adult_covid_confirmed_40-49,previous_day_admission_adult_covid_confirmed_50-59,previous_day_admission_adult_covid_confirmed_60-69,previous_day_admission_adult_covid_confirmed_70-79,previous_day_admission_adult_covid_confirmed_80+,previous_day_admission_adult_covid_confirmed_unknown,critical_staffing_shortage_today_yes
0,AL,2020/01/01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,HI,2020/01/01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,IN,2020/01/01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,LA,2020/01/01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,MN,2020/01/01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
# Create a admission day column for the admission columns
hos["date"] = pd.to_datetime(hos["date"])
hos["admission_date"] = hos["date"] - timedelta(days=1)
hos.head()

,state,date,previous_day_admission_adult_covid_confirmed_18-19,previous_day_admission_adult_covid_confirmed_20-29,previous_day_admission_adult_covid_confirmed_30-39,previous_day_admission_adult_covid_confirmed_40-49,previous_day_admission_adult_covid_confirmed_50-59,previous_day_admission_adult_covid_confirmed_60-69,previous_day_admission_adult_covid_confirmed_70-79,previous_day_admission_adult_covid_confirmed_80+,previous_day_admission_adult_covid_confirmed_unknown,critical_staffing_shortage_today_yes,admission_date
0,AL,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-12-31
1,HI,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-12-31
2,IN,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-12-31
3,LA,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-12-31
4,MN,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2019-12-31

In [7]:
# Rename columns
column_mapping = {
    "previous_day_admission_adult_covid_confirmed_18-19": "admission_18-19",
    "previous_day_admission_adult_covid_confirmed_20-29": "admission_20-29",
    "previous_day_admission_adult_covid_confirmed_30-39": "admission_30-39",
    "previous_day_admission_adult_covid_confirmed_40-49": "admission_40-49",
    "previous_day_admission_adult_covid_confirmed_50-59": "admission_50-59",
    "previous_day_admission_adult_covid_confirmed_60-69": "admission_60-69",
    "previous_day_admission_adult_covid_confirmed_70-79": "admission_70-79",
    "previous_day_admission_adult_covid_confirmed_80+": "admission_80+",
    "previous_day_admission_adult_covid_confirmed_unknown": "admission_unknown",
    "critical_staffing_shortage_today_yes": "num_hospital_shortage_staff"
}
hos = hos.rename(columns=column_mapping)
hos.columns

Index(['state', 'date', 'admission_18-19', 'admission_20-29',
       'admission_30-39', 'admission_40-49', 'admission_50-59',
       'admission_60-69', 'admission_70-79', 'admission_80+',
       'admission_unknown', 'num_hospital_shortage_staff'],
      dtype='object')

In [19]:
hos.columns

Index(['state', 'date', 'admission_18-19', 'admission_20-29',
       'admission_30-39', 'admission_40-49', 'admission_50-59',
       'admission_60-69', 'admission_70-79', 'admission_80+',
       'admission_unknown', 'num_hospital_shortage_staff', 'admission_date'],
      dtype='object')

In [6]:
hos_summary = hos[['admission_18-19', 'admission_20-29',
      'admission_30-39', 'admission_40-49', 'admission_50-59',
      'admission_60-69', 'admission_70-79', 'admission_80+',
      'admission_unknown', 'admission_date']].groupby('admission_date').sum().reset_index()
hos_summary = pd.melt(hos_summary, id_vars=['admission_date'], var_name="age_group", value_name="new_hospitalization_cases")
hos_summary.head()

KeyError: "['admission_date'] not in index"

In [8]:
# Change the values
value_mapping = {
    'admission_18-19': "18 to 19",
    'admission_20-29': "20 to 29",
    'admission_30-39': "30 to 39",
    'admission_40-49': "40 to 49",
    'admission_50-59': "50 to 59",
    'admission_60-69': "60 to 69",
    'admission_70-79': "70 to 79",
    'admission_80+': "80+",
    'admission_unknown': "unknown"
}
hos_summary["age_group"] = hos_summary['age_group'].replace(value_mapping)
hos_summary['age_group'].unique()

NameError: name 'hos_summary' is not defined